# Generated by Django 5.1.2 on 2024-10-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("BUSINESS", "Business"),
                    ("PERSONAL", "Personal"),
                    ("IMPORTANT", "Important"),
                ],
                default="PERSONAL",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
