# Generated by Django 5.1.2 on 2024-10-29 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0002_alter_post_category_alter_post_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Posts",
        ),
    ]
